<?php
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Product;

$products = [
    // Smartphones
    [
        'name' => 'iPhone 16 Pro Max',
        'description' => 'شريحة A18 Pro الجبارة، كاميرا بدقة 48 ميجابكسل مع تقريب بصري 5x، شاشة Super Retina XDR بقياس 6.9 إنش مع ميزة ProMotion وتصميم من التيتانيوم.',
        'price' => 1199.99,
        'old_price' => 1299.99,
        'rating' => 4.9,
        'reviews_count' => 142,
        'category' => 'هواتف ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 25,
    ],
    [
        'name' => 'Samsung Galaxy S25 Ultra',
        'description' => 'معالج Snapdragon 8 Elite، قلم S-Pen مدمج، كاميرا بدقة 200 ميجابكسل مدعومة بذكاء Galaxy AI الفائق وشاشة Dynamic AMOLED 2X مسطحة ومبهرة.',
        'price' => 1249.99,
        'old_price' => 1399.99,
        'rating' => 4.8,
        'reviews_count' => 98,
        'category' => 'هواتف ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 18,
    ],
    [
        'name' => 'Google Pixel 9 Pro XL',
        'description' => 'شريحة Google Tensor G4، ميزات Gemini الذكية المتقدمة، شاشة Super Actua فائقة السطوع وأفضل نظام تصوير فوتوغرافي بالذكاء الاصطناعي.',
        'price' => 1099.00,
        'old_price' => 1199.00,
        'rating' => 4.7,
        'reviews_count' => 64,
        'category' => 'هواتف ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 15,
    ],
    [
        'name' => 'OnePlus 12',
        'description' => 'معالج Snapdragon 8 Gen 3، شاشة 2K ProXDR بتردد 120Hz، شحن فائق السرعة بقدرة 100W وبطارية ضخمة بسعة 5400 مللي أمبير مع كاميرات Hasselblad.',
        'price' => 799.99,
        'old_price' => 899.99,
        'rating' => 4.6,
        'reviews_count' => 52,
        'category' => 'هواتف ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 22,
    ],
    [
        'name' => 'Xiaomi 14 Ultra',
        'description' => 'كاميرات لايكا الاحترافية بحساس 1 إنش، عدسات متطورة متغيرة الفتحة، تصوير سينمائي 8K وهيكل من السيراميك الفاخر.',
        'price' => 1149.00,
        'old_price' => 1249.00,
        'rating' => 4.8,
        'reviews_count' => 41,
        'category' => 'هواتف ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 14,
    ],

    // Laptops
    [
        'name' => 'MacBook Pro M3 Max (16-inch)',
        'description' => 'أقوى حاسوب محمول للمحترفين بشريحة M3 Max مع 16 نواة CPU و 40 نواة GPU، ذاكرة موحدة 48GB، وشاشة Liquid Retina XDR مبهرة.',
        'price' => 3499.00,
        'old_price' => 3799.00,
        'rating' => 4.9,
        'reviews_count' => 115,
        'category' => 'حواسب محمولة',
        'image_url' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 10,
    ],
    [
        'name' => 'Dell XPS 16 OLED',
        'description' => 'معالج Intel Core Ultra 9، كرت شاشة RTX 4070، شاشة 4K OLED تعمل باللمس، وتصميم أنيق وعصري من الألمنيوم وألياف الكربون.',
        'price' => 2399.50,
        'old_price' => 2699.00,
        'rating' => 4.6,
        'reviews_count' => 43,
        'category' => 'حواسب محمولة',
        'image_url' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 12,
    ],
    [
        'name' => 'ASUS ROG Zephyrus G16 (2024)',
        'description' => 'لابتوب ألعاب متطور ونحيف بشاشة OLED بتردد 240Hz، معالج Intel Core Ultra 9 وكرت RTX 4080 لتجربة ألعاب لا تضاهى.',
        'price' => 2499.00,
        'old_price' => 2799.00,
        'rating' => 4.8,
        'reviews_count' => 77,
        'category' => 'حواسب محمولة',
        'image_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 8,
    ],
    [
        'name' => 'MacBook Air M3 (13-inch)',
        'description' => 'خفيف وسريع بشكل لا يصدق مع بطارية تدوم حتى 18 ساعة، بدون مروحة وهدوء تام، شاشة Liquid Retina قياس 13.6 إنش.',
        'price' => 1099.00,
        'old_price' => 1199.00,
        'rating' => 4.9,
        'reviews_count' => 189,
        'category' => 'حواسب محمولة',
        'image_url' => 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 30,
    ],

    // Audio & Headphones
    [
        'name' => 'Sony WH-1000XM5',
        'description' => 'سماعات الرأس الرائدة عالمياً في عزل الضوضاء، نقاء صوتي فائق الدقة Hi-Res، بطارية تدوم 30 ساعة مع شحن سريع وميكروفونات ذكية.',
        'price' => 349.99,
        'old_price' => 399.99,
        'rating' => 4.8,
        'reviews_count' => 230,
        'category' => 'سماعات',
        'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 45,
    ],
    [
        'name' => 'AirPods Pro (2nd Gen) USB-C',
        'description' => 'إلغاء نشط للضوضاء يصل إلى ضعفي الجيل السابق، ميزة الصوت المكاني المخصص، شفافية الصوت التكيفية ومنفذ شحن MagSafe USB-C.',
        'price' => 229.00,
        'old_price' => 249.00,
        'rating' => 4.9,
        'reviews_count' => 312,
        'category' => 'سماعات',
        'image_url' => 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 60,
    ],
    [
        'name' => 'Bose QuietComfort Ultra',
        'description' => 'صوت مكاني غامر يجعلك في قلب الحدث، إلغاء ضوضاء من الطراز العالمي، ووسائد أذن من الجلد فائق النعومة لراحة تدوم طوال اليوم.',
        'price' => 379.00,
        'old_price' => 429.00,
        'rating' => 4.7,
        'reviews_count' => 88,
        'category' => 'سماعات',
        'image_url' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 20,
    ],
    [
        'name' => 'Marshall Stanmore III Bluetooth',
        'description' => 'مكبر صوت منزلي كلاسيكي بتصميم أيقوني، صوت ستيريو عريض يملأ الغرفة مع نقاء صوتي قوي وباس عميق.',
        'price' => 379.99,
        'old_price' => 399.99,
        'rating' => 4.8,
        'reviews_count' => 54,
        'category' => 'سماعات',
        'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 15,
    ],

    // Smartwatches
    [
        'name' => 'Apple Watch Ultra 2',
        'description' => 'ساعة الرياضات والمغامرات الأقوى بهيكل من التيتانيوم 49 مم، سطوع شاشة يصل إلى 3000 شمعة، نظام GPS دقيق مزدوج التردد وبطارية تدوم حتى 72 ساعة.',
        'price' => 799.00,
        'old_price' => 849.00,
        'rating' => 4.9,
        'reviews_count' => 165,
        'category' => 'ساعات ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 28,
    ],
    [
        'name' => 'Samsung Galaxy Watch Ultra',
        'description' => 'تصميم صلب مقاوم للصدمات، مستشعرات BioActive المتطورة لقياس الصحة واللياقة بدقة فائقة، ومقاومة للماء حتى عمق 100 متر.',
        'price' => 649.99,
        'old_price' => 699.99,
        'rating' => 4.7,
        'reviews_count' => 82,
        'category' => 'ساعات ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 20,
    ],
    [
        'name' => 'Garmin Fenix 8 Solar',
        'description' => 'الساعة الذكية الأفضل للرياضيين ومحبي التخييم مع شحن بالطاقة الشمسية، خرائط طوبوغرافية ملونة مدمجة وبطارية تعمل لأسابيع دون شحن.',
        'price' => 999.00,
        'old_price' => 1099.00,
        'rating' => 4.9,
        'reviews_count' => 73,
        'category' => 'ساعات ذكية',
        'image_url' => 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 12,
    ],

    // Tablets & Accessories
    [
        'name' => 'iPad Pro M4 (13-inch OLED)',
        'description' => 'أنحف جهاز أنتجته آبل على الإطلاق بسماكة 5.1 مم، شاشة Ultra Retina XDR بتقنية OLED الترادفية وشريحة M4 المذهلة لقوة أداء لا تضاهى.',
        'price' => 1299.00,
        'old_price' => 1399.00,
        'rating' => 4.9,
        'reviews_count' => 140,
        'category' => 'إكسسوارات',
        'image_url' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 16,
    ],
    [
        'name' => 'Logitech MX Master 3S Wireless',
        'description' => 'ماوس الإنتاجية الاحترافي بعجلة MagSpeed المغناطيسية الفائقة، نقرات صامتة تماماً، ومستشعر دقيق 8000 DPI يعمل على كافة الأسطح بما فيها الزجاج.',
        'price' => 99.99,
        'old_price' => 119.99,
        'rating' => 4.9,
        'reviews_count' => 420,
        'category' => 'إكسسوارات',
        'image_url' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 70,
    ],
    [
        'name' => 'Anker 737 Power Bank 140W',
        'description' => 'بطارية شحن متنقلة ضخمة بسعة 24,000 مللي أمبير مع شاشة رقمية ملونة وشحن فائق السرعة بقدرة 140W لشحن الهواتف والحواسب المحمولة معاً.',
        'price' => 149.99,
        'old_price' => 169.99,
        'rating' => 4.8,
        'reviews_count' => 180,
        'category' => 'إكسسوارات',
        'image_url' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 50,
    ],
    [
        'name' => 'Keychron Q1 Pro Wireless Mechanical Keyboard',
        'description' => 'لوحة مفاتيح ميكانيكية مخصصة من الألمنيوم بالكامل، مفاتيح قابلة للتبديل السريع Hot-Swappable، وإضاءة RGB مذهلة مع دعم Mac و Windows.',
        'price' => 199.00,
        'old_price' => 219.00,
        'rating' => 4.8,
        'reviews_count' => 95,
        'category' => 'إكسسوارات',
        'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
        'is_featured' => false,
        'stock' => 25,
    ],
    [
        'name' => 'DJI Osmo Pocket 3 Creator Combo',
        'description' => 'كاميرا جيب مدمجة بحساس 1 إنش، تثبيت ميكانيكي ثلاثي المحاور، شاشة لمس دوارة 2 إنش، وتصوير فيديو سينمائي 4K/120fps.',
        'price' => 669.00,
        'old_price' => 719.00,
        'rating' => 4.9,
        'reviews_count' => 110,
        'category' => 'إكسسوارات',
        'image_url' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80',
        'is_featured' => true,
        'stock' => 14,
    ],
];

\Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
Product::truncate();
\Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

foreach ($products as $p) {
    Product::create($p);
}

echo "SUCCESSFULLY_INSERTED_" . count($products) . "_PRODUCTS\n";
